
#### DFI RPC credentials
[DFI.RPC]
Hostname = "localhost"
Port = 19554
User = "test"
Password = "test"
REGTEST = false

[DFI.ACCOUNT]
PRIVKEY = "XXX"

[TXN.ADDR]
addrFrom = "mswsMVsyGMj1FzDMbbxw2QW3KvQAv2FKiy"
addrTo = "mnyRQwXpsAPDmrzrLdqfxZuc1v5e5HQt4d"
tokenFrom = "MyToken2#130" # Used for poolswap
tokenTo = "MyToken3#131"
poolpair = "LP130112"

#### Enabled transactions
[TXN.TYPE]
UTXO = true
MINT_TOKEN = true
UTXO_TO_ACC = true
ACC_TO_UTXO = true
ACC_TO_ACC = true
ADD_LIQUIDITY = true
POOL_SWAP = true
