
#### DFI RPC credentials
[DFI.RPC]
Hostname = "0.0.0.0"
Port = 18554
User = "test"
Password = "test"
REGTEST = false

#### Address and tokens for test
[TXN.ADDR]
addrFrom = "7Jw72Q9yGJ1UWCXdQcUwkwSX48mkvdV2sS"
addrTo = "7Jw72Q9yGJ1UWCXdQcUwkwSX48mkvdV2sS"
tokenFrom = "DFI" # Used for poolswap
tokenTo = "MOCK"
poolpair = "MOCK-DFI"

#### Enabled transactions
[TXN.TYPE]
UTXO = true
MINT_TOKEN = false
UTXO_TO_ACC = true
ACC_TO_UTXO = true
ACC_TO_ACC = true
ADD_LIQUIDITY = false
POOL_SWAP = true
